version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ${DB_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
        mode: host
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: ${ADMINER_CONTAINER}
    restart: always
    ports:
      - target: 8080
        published: ${ADMINER_PORT:-8080}
        protocol: tcp
        mode: host
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
