version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: batch_etl_demo
    environment:
      POSTGRES_USER: batch_etl_user
      POSTGRES_PASSWORD: batch_etl_pass
      POSTGRES_DB: batch_etl_db
    ports:
      - "5432:5432" # If 5432 is busy on your host, change to "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: batch_etl_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
